# Generated by Django 3.0.6 on 2020-05-30 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_humidityreading_temperaturereading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidityreading',
            name='reading',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='temperaturereading',
            name='reading',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
